### ISSUE TITLE
Error using latest parent code

### ISSUE THREAD

**Issue by halfrican99503** [Gelix/HubitatTailwind#2]
I sent you a PM through HE forum but wanted to make sure you saw this so I'm copying here.  Latest code is throwing an error when trying to open/close a door from the child device, works fine if I open/close from parent.

![image](https://user-images.githubusercontent.com/31705696/133864905-b5826d04-232b-4813-8b50-8dce3fd0d21f.png)

**Comment by Gelix** [comment]
I forgot the child driver when I uploaded the last changes.  Updated it!  Let me know if that fixes this.

**Comment by halfrican99503** [comment]
yes, fixed! Thanks
